services:
#  mysql:
#    image: mysql
#    ports:
#      - 3306:3306
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=todolist

  web:
    build: todo-web
    ports:
      - "80:80"
  todo:
    build: .